name: CI

on: [push, pull_request]  # Déclenche le workflow à chaque push ou pull request

jobs:
  test:
    runs-on: ubuntu-latest 

    steps:
      # Étape 1 : Récupère le code
      - uses: actions/checkout@v3

      # Étape 2 : Configure Python
      - name: Set up Python
        uses: actions/setup-python@v5
        with:
          python-version: "3.10"  # Version de Python à utiliser
      
      - name: Set API_URL
        env:
          API_URL: ${{ secrets.API_URL }}
        run: echo "API_URL is set"

      # Étape 3 : Installe les dépendances
      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install -r requirements.txt
          pip install pytest

      # Étape 4 : Exécute les tests
      - name: Run tests
        run: pytest tests/